#!/usr/bin/env python3
"""
Generate docs/boards/FIRMWARE_EXERCISE_MATRIX.md.

Companion to scripts/generate_validation_status.py. That script answers "is the
model right vs silicon?"; this one answers "does any real firmware actually RUN
against the model?".

Two sources, by design:

1. RUBRIC coverage (clock/gpio/uart/timer/dma/irq/i2c/spi/adc/pwm/wdt/rtc/can/
   rmt) is AUTHORITATIVE from docs/coverage/tier1-matrix.json — the committed,
   ratchet-gated output of the Tier-1 fixture sims. It is NOT hand-maintained
   here: each chip's tier1 fixture is real firmware that drives those peripheral
   classes and self-reports PASS, so the matrix cannot drift from reality.

2. BEYOND the rubric — functional device reads (a real driver decoding a sensor
   over a bus), chip-specific advanced peripherals, and shims — lives in
   validation/firmware_exercise.yaml, which tier1 does not cover.

A first-pass hand-authored matrix under-counted the STM32 family ~4x because it
read only the banner-level survival tests and missed the tier1 fixtures. Sourcing
the rubric from tier1-matrix.json makes that class of error impossible.

Modes:
  (default)   regenerate docs/boards/FIRMWARE_EXERCISE_MATRIX.md in place
  --check     fail if the committed doc is stale (run in CI)

Needs PyYAML.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML required — `pip install pyyaml`", file=sys.stderr)
    sys.exit(2)

CORE_ROOT = Path(__file__).resolve().parent.parent
YAML_SRC = CORE_ROOT / "validation" / "firmware_exercise.yaml"
TIER1_JSON = CORE_ROOT / "docs" / "coverage" / "tier1-matrix.json"
OUT_DOC = CORE_ROOT / "docs" / "boards" / "FIRMWARE_EXERCISE_MATRIX.md"

# Column order for the rubric grid (bring-up rubric, then typical peripherals,
# then the two extra classes some chips declare).
RUBRIC = [
    "clock", "gpio", "uart", "timer", "dma", "irq",
    "i2c", "spi", "adc", "pwm", "wdt", "rtc", "can", "rmt",
]

CELL = {"pass": "🟢", "unrecorded": "🟠", "na": "·", "partial": "◐", "blocked": "🔴"}

# Closed vocabulary for `functional[].gate`. A typo must fail the generator, not
# silently render an entry with no badge (a claim erased by a spelling mistake).
GATE_BADGES = {
    "pr": " (PR gate)",
    "release": " (release CI)",
    "nightly": " (nightly CI)",
    "ignored": " (on-demand)",
    "none": " (ungated)",
}


def status(cell) -> str:
    if isinstance(cell, dict):
        return cell.get("status", "")
    return str(cell or "")


def list_field(chip_id: str, doc: dict, key: str) -> list:
    """The list value of `key`, or [] when absent/null. Anything else is a
    schema error — a mapping or string here silently renders garbage."""
    value = doc.get(key)
    if value is None:
        return []
    if not isinstance(value, list):
        raise ValueError(
            f"chip {chip_id}: `{key}` must be a list, got {type(value).__name__}"
        )
    return value


def render(tier1: dict, ydoc: dict) -> str:
    chips_yaml = {c["id"]: c for c in ydoc.get("chips", [])}
    L: list[str] = []
    L.append("<!-- GENERATED by scripts/generate_firmware_exercise_matrix.py — DO NOT EDIT BY HAND.")
    L.append("     Rubric coverage: docs/coverage/tier1-matrix.json (authoritative, ratchet-gated).")
    L.append("     Beyond-rubric layer: validation/firmware_exercise.yaml. -->")
    L.append("")
    L.append("# Firmware-exercise matrix")
    L.append("")
    L.append(
        "Where `VALIDATION_STATUS.md` asks *\"is the model right vs silicon?\"*, this "
        "matrix asks the complementary question: **does a real booting firmware "
        "actually RUN against the model?** A model is only counted when a booting "
        "firmware drives it — a banner-only boot or a register-poke unit test does not."
    )
    L.append("")

    # ── Part 1: rubric coverage (authoritative) ────────────────────────────
    L.append("## Rubric coverage — authoritative, from the Tier-1 fixtures")
    L.append("")
    L.append(
        "Each chip's Tier-1 fixture is **real firmware** that drives these peripheral "
        "classes and self-reports `PASS` over UART; the grid below is generated from "
        "`docs/coverage/tier1-matrix.json` (ratchet-gated, so it cannot drift). "
        "🟢 driven-by-firmware · 🟠 modeled but fixture does not exercise it · "
        "· not modeled on this chip (n/a)."
    )
    L.append("")
    header = "| chip | " + " | ".join(RUBRIC) + " | **proven** |"
    sep = "|------|" + "|".join("---" for _ in RUBRIC) + "|------|"
    L.append(header)
    L.append(sep)
    tot_pass = tot_unrec = 0
    for chip in sorted(tier1.keys()):
        row = tier1[chip]
        cells = []
        npass = 0
        for cls in RUBRIC:
            st = status(row.get(cls))
            cells.append(CELL.get(st, "" if st == "" else st[:1]))
            if st == "pass":
                npass += 1
            if st == "unrecorded":
                tot_unrec += 1
        tot_pass += npass
        L.append(f"| `{chip}` | " + " | ".join(cells) + f" | **{npass}** |")
    L.append("")
    L.append(
        f"> **{tot_pass} rubric cells are driven by real firmware** across {len(tier1)} "
        f"chips; {tot_unrec} are modeled-but-unrecorded (see below). Most chips drive "
        "9–13 of the common peripheral classes — the STM32 family included."
    )
    L.append("")
    # Surface every unrecorded cell explicitly (no silent gaps).
    unrec = []
    for chip in sorted(tier1.keys()):
        for cls in RUBRIC:
            if status(tier1[chip].get(cls)) == "unrecorded":
                unrec.append(f"`{chip}`/{cls}")
    if unrec:
        L.append("**Unrecorded rubric cells (modeled, fixture does not drive them):** "
                 + ", ".join(unrec) + ".")
        L.append("")

    # ── Part 2: beyond the rubric ──────────────────────────────────────────
    L.append("## Beyond the rubric — functional reads, advanced peripherals, shims")
    L.append("")
    L.append(
        "What the rubric grid does not cover: real drivers decoding a sensor/protocol "
        "over a bus (the gold standard), chip-specific advanced peripherals, and shims "
        "(hardcoded stubs or declarative register files with no engine behind them). "
        "From `validation/firmware_exercise.yaml`."
    )
    L.append("")
    for cid in [c["id"] for c in ydoc.get("chips", [])]:
        c = chips_yaml[cid]
        L.append(f"### `{cid}`")
        L.append("")
        if c.get("headline"):
            L.append(f"_{c['headline']}_")
            L.append("")
        func = c.get("functional") or []
        if func:
            L.append("**Functional device/protocol reads** (real driver, decoded value):")
            for f in func:
                gate = f.get("gate") or "none"
                if gate not in GATE_BADGES:
                    raise ValueError(
                        f"chip {cid}: functional entry has unknown gate {gate!r}"
                    )
                badge = GATE_BADGES[gate]
                L.append(f"- {f['what']} — `{f.get('fw','?')}` · {f.get('ev','')}{badge}")
            L.append("")
        adv = list_field(cid, c, "advanced_unit_only")
        if adv:
            L.append("**Advanced peripherals — unit-tested only** (no firmware drives them): "
                     + ", ".join(f"`{a}`" for a in adv))
            L.append("")
        dead = list_field(cid, c, "advanced_dead")
        if c.get("dead_note") and not dead:
            raise ValueError(
                f"chip {cid}: `dead_note` is set but `advanced_dead` is empty — "
                "remove the note or restore the entry it explains"
            )
        if dead:
            ex = ", ".join(f"`{e}`" for e in dead)
            L.append(f"**Dead** ({len(dead)} modeled, never exercised): {ex}")
            if c.get("dead_note"):
                L.append("")
                L.append(f"  > ⚠ {c['dead_note']}")
            L.append("")
        shim = c.get("shim") or []
        if shim:
            L.append("**Shims** (hardcoded stubs or engine-less declarative register files — not real fidelity):")
            for s in shim:
                note = f" — {s['note']}" if s.get("note") else ""
                L.append(f"- `{s['p']}` ({s.get('ev','')}){note}")
            L.append("")
    return "\n".join(L).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if committed doc is stale")
    args = ap.parse_args()

    tier1 = json.loads(TIER1_JSON.read_text())
    ydoc = yaml.safe_load(YAML_SRC.read_text())

    chips_on_disk = {
        p.stem
        for p in (CORE_ROOT / "configs" / "chips").glob("*.yaml")
        if not p.stem.startswith("ci-fixture")
    }
    documented_list = [c["id"] for c in ydoc.get("chips", [])]
    duplicates = sorted({cid for cid in documented_list if documented_list.count(cid) > 1})
    if duplicates:
        print(
            "ERROR: firmware_exercise.yaml has more than one entry for:\n  "
            + "\n  ".join(duplicates),
            file=sys.stderr,
        )
        return 1
    for c in ydoc.get("chips", []):
        if not str(c.get("headline") or "").strip():
            print(
                f"ERROR: firmware_exercise.yaml entry {c.get('id', '?')!r} has no headline.\n"
                "Every top-level chip needs an entry, and an entry with no beyond-rubric\n"
                "content must say so in its headline — a bare `- id: x` is not enough.",
                file=sys.stderr,
            )
            return 1
    documented = set(documented_list)
    missing = sorted(chips_on_disk - documented)
    extra = sorted(documented - chips_on_disk)
    if missing:
        print(
            "ERROR: chip(s) with no beyond-rubric entry in "
            "validation/firmware_exercise.yaml:\n  " + "\n  ".join(missing) +
            "\nAdd an entry — an empty one is valid when the chip has no "
            "beyond-rubric content, but its headline must say so.",
            file=sys.stderr,
        )
        return 1
    if extra:
        print(
            "ERROR: firmware_exercise.yaml names chip(s) with no top-level "
            "`configs/chips/<id>.yaml`:\n  " + "\n  ".join(extra),
            file=sys.stderr,
        )
        if any(cid.startswith("ci-fixture") for cid in extra):
            print(
                "       `ci-fixture-*` ids are CI fixtures, not chips — they are "
                "out of scope and cannot be ledgered.",
                file=sys.stderr,
            )
        return 1

    rendered = render(tier1, ydoc)

    if args.check:
        existing = OUT_DOC.read_text() if OUT_DOC.exists() else ""
        if existing != rendered:
            print(
                f"ERROR: {OUT_DOC.relative_to(CORE_ROOT)} is out of date.\n"
                "       Run: python3 scripts/generate_firmware_exercise_matrix.py",
                file=sys.stderr,
            )
            return 1
        return 0

    OUT_DOC.write_text(rendered)
    print(f"wrote {OUT_DOC.relative_to(CORE_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
